version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - application-network
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8888:8081
    networks:
      - application-network
  hapi-server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: hapi-server/latest
    depends_on:
      - mongo
    ports:
      - 3000:3000
    networks:
      - application-network
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: client-app
    ports:
      - 9000:80
    networks:
      - application-network
networks:
  application-network:
    driver: bridge
